version: '2'
services:
  postgres:
    image: javaland/example-postgres:1.0
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DATABASE=recipes
